// This file was generated by img2gb, DO NOT EDIT

#ifndef _LEVEL01_TILEMAP_H
#define _LEVEL01_TILEMAP_H

extern const UINT8 LEVEL01_TILEMAP[];
#define LEVEL01_TILEMAP_WIDTH 20
#define LEVEL01_TILEMAP_HEIGHT 18


#endif
