// This file was generated by img2gb, DO NOT EDIT

#ifndef _WINDOW_TILEMAP_H
#define _WINDOW_TILEMAP_H

extern const UINT8 WINDOW_TILEMAP[];
#define WINDOW_TILEMAP_WIDTH 20
#define WINDOW_TILEMAP_HEIGHT 2


#endif
